#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: meetingList_screen
  screens: 
    meetingList_screen: &meetingList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Meeting
      title: _("List of %s %2s", ngettext('Meeting', 'Meeting(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            meetingEdit_screen: true
          dialogs: 
            meetingDel_dialog: true
          default: meetingEdit_screen
      options: 
        title: _("Options")
        screens: 
          meetingNew_screen: true
        dialogs: 
          meetingDel_dialog: true
    meetingNew_screen: &meetingNew_screenLink 
      <<: *Meeting
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Meeting', 'Meeting(s)', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          createdAt: true
    meetingEdit_screen: &meetingEdit_screenLink 
      <<: *Meeting
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Meeting', 'Meeting(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          createdAt: true
  dialogs: 
    meetingDel_dialog: 
      <<: *Meeting
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Meeting', 'Meeting(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Meeting', 'Meeting(s)', 1))
      message: _("%s successfully deleted.", ngettext('Meeting', 'Meeting(s)', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
