#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: relTagSpeakerList_screen
  screens: 
    relTagSpeakerList_screen: &relTagSpeakerList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *RelTagSpeaker
      title: _("List of %s %2s", ngettext('Rel tag speaker', 'Rel tag speaker(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            relTagSpeakerEdit_screen: true
          dialogs: 
            relTagSpeakerDel_dialog: true
          default: relTagSpeakerEdit_screen
      options: 
        title: _("Options")
        screens: 
          relTagSpeakerNew_screen: true
        dialogs: 
          relTagSpeakerDel_dialog: true
    relTagSpeakerNew_screen: &relTagSpeakerNew_screenLink 
      <<: *RelTagSpeaker
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rel tag speaker', 'Rel tag speaker(s)', 1))
      shortcutOption: N
    relTagSpeakerEdit_screen: &relTagSpeakerEdit_screenLink 
      <<: *RelTagSpeaker
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Rel tag speaker', 'Rel tag speaker(s)', 1), "[format| (%item%)]")
  dialogs: 
    relTagSpeakerDel_dialog: 
      <<: *RelTagSpeaker
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rel tag speaker', 'Rel tag speaker(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Rel tag speaker', 'Rel tag speaker(s)', 1))
      message: _("%s successfully deleted.", ngettext('Rel tag speaker', 'Rel tag speaker(s)', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
