#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: relTagSchedueleList_screen
  screens: 
    relTagSchedueleList_screen: &relTagSchedueleList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *RelTagScheduele
      title: _("List of %s %2s", ngettext('Rel tag scheduele', 'Rel tag scheduele(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            relTagSchedueleEdit_screen: true
          dialogs: 
            relTagSchedueleDel_dialog: true
          default: relTagSchedueleEdit_screen
      options: 
        title: _("Options")
        screens: 
          relTagSchedueleNew_screen: true
        dialogs: 
          relTagSchedueleDel_dialog: true
    relTagSchedueleNew_screen: &relTagSchedueleNew_screenLink 
      <<: *RelTagScheduele
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rel tag scheduele', 'Rel tag scheduele(s)', 1))
      shortcutOption: N
    relTagSchedueleEdit_screen: &relTagSchedueleEdit_screenLink 
      <<: *RelTagScheduele
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Rel tag scheduele', 'Rel tag scheduele(s)', 1), "[format| (%item%)]")
  dialogs: 
    relTagSchedueleDel_dialog: 
      <<: *RelTagScheduele
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rel tag scheduele', 'Rel tag scheduele(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Rel tag scheduele', 'Rel tag scheduele(s)', 1))
      message: _("%s successfully deleted.", ngettext('Rel tag scheduele', 'Rel tag scheduele(s)', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
