#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: scheduleList_screen
  screens: 
    scheduleList_screen: &scheduleList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Schedule
      title: _("List of %s %2s", ngettext('Schedule', 'Schedule(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            scheduleEdit_screen: true
          dialogs: 
            scheduleDel_dialog: true
          default: scheduleEdit_screen
      options: 
        title: _("Options")
        screens: 
          scheduleNew_screen: true
        dialogs: 
          scheduleDel_dialog: true
    scheduleNew_screen: &scheduleNew_screenLink 
      <<: *Schedule
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Schedule', 'Schedule(s)', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          lastModified: true
    scheduleEdit_screen: &scheduleEdit_screenLink 
      <<: *Schedule
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Schedule', 'Schedule(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          lastModified: true
  dialogs: 
    scheduleDel_dialog: 
      <<: *Schedule
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Schedule', 'Schedule(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Schedule', 'Schedule(s)', 1))
      message: _("%s successfully deleted.", ngettext('Schedule', 'Schedule(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    PictureDownload_command: 
      <<: *Schedule
      controller: File
      action: force-download
      mainColumn: picture
    PictureUpload_command: 
      <<: *Schedule
      controller: File
      action: upload
      mainColumn: picture
    PicturePreview_command: 
      <<: *Schedule
      controller: File
      action: preview
      mainColumn: picture
    IconDownload_command: 
      <<: *Schedule
      controller: File
      action: force-download
      mainColumn: icon
    IconUpload_command: 
      <<: *Schedule
      controller: File
      action: upload
      mainColumn: icon
    IconPreview_command: 
      <<: *Schedule
      controller: File
      action: preview
      mainColumn: icon
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
