#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: speakerList_screen
  screens: 
    speakerList_screen: &speakerList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Speaker
      title: _("List of %s %2s", ngettext('Speaker', 'Speaker(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            speakerEdit_screen: true
          dialogs: 
            speakerDel_dialog: true
          default: speakerEdit_screen
      options: 
        title: _("Options")
        screens: 
          speakerNew_screen: true
        dialogs: 
          speakerDel_dialog: true
    speakerNew_screen: &speakerNew_screenLink 
      <<: *Speaker
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Speaker', 'Speaker(s)', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          lastModified: true
    speakerEdit_screen: &speakerEdit_screenLink 
      <<: *Speaker
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Speaker', 'Speaker(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          lastModified: true
  dialogs: 
    speakerDel_dialog: 
      <<: *Speaker
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Speaker', 'Speaker(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Speaker', 'Speaker(s)', 1))
      message: _("%s successfully deleted.", ngettext('Speaker', 'Speaker(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    PictureDownload_command: 
      <<: *Speaker
      controller: File
      action: force-download
      mainColumn: picture
    PictureUpload_command: 
      <<: *Speaker
      controller: File
      action: upload
      mainColumn: picture
    PicturePreview_command: 
      <<: *Speaker
      controller: File
      action: preview
      mainColumn: picture
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
