production: 
  class: \Librecon\Model\KlearRolesSections
  fields: 
    klearRoleId: 
      title: _('Klear role id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Librecon\Mapper\Sql\KlearRoles
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
      default: true
    klearSectionId: 
      title: _('Klear section id')
      type: select
      required: true
      source: 
        data: mapper
        config: 
          mapperName: \Librecon\Mapper\Sql\KlearSections
          fieldName: 
            fields: 
              - name
            template: '%name%'
          order: name
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
