production: 
  class: \Librecon\Model\Sponsors
  fields: 
    name: 
      title: ngettext('Name', 'Names', 1)
      type: text
      required: true
      default: true
    orderField: 
      title: _('Order field')
      type: number
      defaultValue: 0
      source: 
        control: Spinner
    logo: 
      title: _('Logo')
      type: file
      source: 
        data: fso
        size_limit: 20M
        options: 
          download: 
            external: true
            type: command
            target: LogoDownload_command
            icon: ui-silk-bullet-disk
            title: _("Download file")
            onNull: hide
          upload: 
            type: command
            target: LogoUpload_command
            title: _("Upload file")
            class: qq-uploader
            onNull: show
          preview: 
            target: LogoPreview_command
            type: command
            class: filePreview
            external: 1
            props: 
              width: 150
              height: 150
              crop: false
            onNull: hide
          previewList: 
            target: LogoPreview_command
            type: command
            class: filePreview
            listController: 1
            external: 1
            props: 
              width: 30
              height: 30
              crop: false
            onNull: hide
    url: 
      title: ngettext('Url', 'Urls', 1)
      type: text
    lastModified: 
      title: _('Last modified')
      type: picker
      defaultValue: CURRENT_TIMESTAMP
      source: 
        control: datetime
        settings: 
          disabled: 'false'
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
