#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedPositionsForExpositor
    data:
      fields:
        companyName: true
        logo: true

production: 
  main: 
    module: klearMatrix
    defaultScreen: expositorList_screen
  screens: 
    expositorList_screen: &expositorList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Expositor
      title: _("List of %s %2s", ngettext('Expositor', 'Expositor(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            expositorEdit_screen: true
          dialogs: 
            expositorDel_dialog: true
          default: expositorEdit_screen
      options: 
        title: _("Options")
        screens: 
          expositorNew_screen: true
        dialogs: 
          expositorDel_dialog: true
    expositorNew_screen: &expositorNew_screenLink 
      <<: *Expositor
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Expositor', 'Expositor(s)', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          lastModified: true
      fixedPositions:
        <<: *fixedPositionsForExpositor
    expositorEdit_screen: &expositorEdit_screenLink 
      <<: *Expositor
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Expositor', 'Expositor(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          lastModified: true
      fixedPositions:
        <<: *fixedPositionsForExpositor
  dialogs: 
    expositorDel_dialog: &expositorDel_dialogLink 
      <<: *Expositor
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Expositor', 'Expositor(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Expositor', 'Expositor(s)', 1))
      message: _("%s successfully deleted.", ngettext('Expositor', 'Expositor(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    LogoDownload_command: 
      <<: *Expositor
      controller: File
      action: force-download
      mainColumn: logo
    LogoUpload_command: 
      <<: *Expositor
      controller: File
      action: upload
      mainColumn: logo
    LogoPreview_command: 
      <<: *Expositor
      controller: File
      action: preview
      mainColumn: logo
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
