production: 
  main: 
    log: 
      writerName: "Null"
      writerParams: 
    sitename: Librecon
    logo: img/logo_librecon_mobile_simple.png
    year: 2014
    lang: es
    langs: 
      es: 
        title: Español
        language: es
        locale: es_ES
      en: 
        title: English
        language: en
        locale: en_US
      eu: 
        title: Euskara
        language: eu
        locale: eu_ES
    jqueryUI: 
#      theme: redmond
      path: /css/style.css
    raw:
      css:
        - "./default/css/style.css"
    cssExtended: 
      silkExtendedIconPath: /img/favicon.ico
    actionHelpers: 
    auth: 
      adapter: Klear_Auth_Adapter_Basic
      title: _("Access denied")
      description: _("Insert your username")
      userMapper: Librecon_Auth_Users
      adapter: Librecon_Auth_Adapter
      session:
        name: klear_librecon
        disableChangeName: true
    timezone: Europe/Madrid
    
  menu: 
    General: 
      title: _("Contenidos")
      description: _("Lista de contenidos")
      submenus: 
        ScheduleList: 
          title: ngettext('Schedule', 'Schedules', 0)
          class: ui-silk-report-user
          description: _("List of %s", ngettext('Schedule', 'Schedules', 0))
        SpeakerList: 
          title: ngettext('Speaker', 'Speaker', 0)
          class: ui-silk-user-gray
          description: _("List of %s", ngettext('Speaker', 'Speakers', 0))
        SponsorsList: 
          title: ngettext('Sponsor', 'Sponsors', 0)
          class: ui-silk-user-suit
          description: _("List of %s", ngettext('Sponsor', 'Sponsors', 0))
        ExpositorList: 
          title: ngettext('Expositor', 'Expositor', 0)
          class: ui-silk-user-orange
          description: _("List of %s", ngettext('Expositor', 'Expositors', 0))
        TxokoList: 
          title: ngettext('Txoko', 'Txoko', 0)
          class: ui-silk-application-home
          description: _("List of %s", ngettext('Txoko', 'Txokos', 0))
        TagsList: 
          title: ngettext('Tag', 'Tags', 0)
          class: ui-silk-tag-blue
          description: _("List of %s", ngettext('Tag', 'Tags', 0))
        LinksList: 
          title: ngettext('Link', 'Links', 0)
          class: ui-silk-world-link
          description: _("List of %s", ngettext('Link', 'Links', 0))
    Asistentes: 
      title: _("Asistentes")
      description: _("Lista de asistentes")
      submenus: 
        AssistantsList: 
          title: ngettext('Assistant', 'Assistants', 0)
          class: ui-silk-group
          description: _("List of %s", ngettext('Assistant', 'Assistants', 0))
        MeetingList: 
          title: ngettext('Meeting', 'Meetings', 0)
          class: ui-silk-report
          description: _("List of %s", ngettext('Meeting', 'Meetings', 0))
    Settings: 
      title: _("Configuración")
      description: _("Configuración")
      submenus: 
        KlearUsersList: 
          title: ngettext('Klear user', 'Klear users', 0)
          class: ui-silk-vcard
          description: _("List of %s", ngettext('Klear user', 'Klear users', 0))
        KlearRolesList: 
          title: ngettext('Rol', 'Roles', 0)
          class: ui-silk-vcard-delete
          description: _("List of %s", ngettext('Klear role', 'Klear roles', 0))
        Dashboard:
          default: true 
          title: _("Panel de control")
          class: ui-silk-bricks
          description: Vista general de todas las entidades
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
