#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: relScheduleSpeakerList_screen
  screens: 
    relScheduleSpeakerList_screen: &relScheduleSpeakerList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *RelScheduleSpeaker
      title: _("List of %s %2s", ngettext('Rel schedule speaker', 'Rel schedule speaker(s)', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            relScheduleSpeakerEdit_screen: true
          dialogs: 
            relScheduleSpeakerDel_dialog: true
          default: relScheduleSpeakerEdit_screen
      options: 
        title: _("Options")
        screens: 
          relScheduleSpeakerNew_screen: true
        dialogs: 
          relScheduleSpeakerDel_dialog: true
    relScheduleSpeakerNew_screen: &relScheduleSpeakerNew_screenLink 
      <<: *RelScheduleSpeaker
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Rel schedule speaker', 'Rel schedule speaker(s)', 1))
      shortcutOption: N
    relScheduleSpeakerEdit_screen: &relScheduleSpeakerEdit_screenLink 
      <<: *RelScheduleSpeaker
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Rel schedule speaker', 'Rel schedule speaker(s)', 1), "[format| (%item%)]")
  dialogs: 
    relScheduleSpeakerDel_dialog: &relScheduleSpeakerDel_dialogLink 
      <<: *RelScheduleSpeaker
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Rel schedule speaker', 'Rel schedule speaker(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Rel schedule speaker', 'Rel schedule speaker(s)', 1))
      message: _("%s successfully deleted.", ngettext('Rel schedule speaker', 'Rel schedule speaker(s)', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
