#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedPositionsForSponsor
    data:
      fields:
        name: true
        logo: true

production: 
  main: 
    module: klearMatrix
    defaultScreen: sponsorsList_screen
  screens: 
    sponsorsList_screen: &sponsorsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Sponsors
      title: _("List of %s %2s", ngettext('Sponsor', 'Sponsors', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            sponsorsEdit_screen: true
          dialogs: 
            sponsorsDel_dialog: true
          default: sponsorsEdit_screen
      options: 
        title: _("Options")
        screens: 
          sponsorsNew_screen: true
        dialogs: 
          sponsorsDel_dialog: true
    sponsorsNew_screen: &sponsorsNew_screenLink 
      <<: *Sponsors
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Sponsor', 'Sponsors', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          lastModified: true
      fixedPositions:
        <<: *fixedPositionsForSponsor
    sponsorsEdit_screen: &sponsorsEdit_screenLink 
      <<: *Sponsors
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Sponsor', 'Sponsors', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          lastModified: true
      fixedPositions:
        <<: *fixedPositionsForSponsor
  dialogs: 
    sponsorsDel_dialog: &sponsorsDel_dialogLink 
      <<: *Sponsors
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Sponsor', 'Sponsors', 1))
      description: _("Do you want to delete this %s?", ngettext('Sponsor', 'Sponsors', 1))
      message: _("%s successfully deleted.", ngettext('Sponsor', 'Sponsors', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    LogoDownload_command: 
      <<: *Sponsors
      controller: File
      action: force-download
      mainColumn: logo
    LogoUpload_command: 
      <<: *Sponsors
      controller: File
      action: upload
      mainColumn: logo
    LogoPreview_command: 
      <<: *Sponsors
      controller: File
      action: preview
      mainColumn: logo
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
