#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

fixedPositions:
  - &fixedPositionsForTxoko
    data:
      fields:
        title: true
        picture: true

production: 
  main: 
    module: klearMatrix
    defaultScreen: txokoList_screen
  screens: 
    txokoList_screen: &txokoList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Txoko
      title: _("List of %s %2s", ngettext('Txoko', 'Txoko(s)', 0), "[format| (%parent%)]")
      fields: 
        blacklist:
          text: true
        options: 
          title: _("Options")
          screens: 
            txokoEdit_screen: true
          dialogs: 
            txokoDel_dialog: true
          default: txokoEdit_screen
      options: 
        title: _("Options")
        screens: 
          txokoNew_screen: true
        dialogs: 
          txokoDel_dialog: true
    txokoNew_screen: &txokoNew_screenLink 
      <<: *Txoko
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Txoko', 'Txoko(s)', 1))
      shortcutOption: N
      fields: 
        blacklist: 
          lastModified: true
      fixedPositions:
        <<: *fixedPositionsForTxoko
    txokoEdit_screen: &txokoEdit_screenLink 
      <<: *Txoko
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Txoko', 'Txoko(s)', 1), "[format| (%item%)]")
      fields: 
        blacklist: 
          lastModified: true
      fixedPositions:
        <<: *fixedPositionsForTxoko
  dialogs: 
    txokoDel_dialog: &txokoDel_dialogLink 
      <<: *Txoko
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Txoko', 'Txoko(s)', 1))
      description: _("Do you want to delete this %s?", ngettext('Txoko', 'Txoko(s)', 1))
      message: _("%s successfully deleted.", ngettext('Txoko', 'Txoko(s)', 1))
      multiItem: 1
      labelOnList: 1
  commands: 
    PictureDownload_command: 
      <<: *Txoko
      controller: File
      action: force-download
      mainColumn: picture
    PictureUpload_command: 
      <<: *Txoko
      controller: File
      action: upload
      mainColumn: picture
    PicturePreview_command: 
      <<: *Txoko
      controller: File
      action: preview
      mainColumn: picture
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
