#include conf.d/mapperList.yaml
#include conf.d/actions.yaml

production: 
  main: 
    module: klearMatrix
    defaultScreen: versionsList_screen
  screens: 
    versionsList_screen: &versionsList_screenLink 
      controller: list
      pagination: 
        items: 25
      <<: *Versions
      title: _("List of %s %2s", ngettext('Version', 'Versions', 0), "[format| (%parent%)]")
      fields: 
        options: 
          title: _("Options")
          screens: 
            versionsEdit_screen: true
          dialogs: 
            versionsDel_dialog: true
          default: versionsEdit_screen
      options: 
        title: _("Options")
        screens: 
          versionsNew_screen: true
        dialogs: 
          versionsDel_dialog: true
    versionsNew_screen: &versionsNew_screenLink 
      <<: *Versions
      controller: new
      class: ui-silk-add
      label: true
      multiInstance: true
      title: _("Add %s", ngettext('Version', 'Versions', 1))
      shortcutOption: N
    versionsEdit_screen: &versionsEdit_screenLink 
      <<: *Versions
      controller: edit
      class: ui-silk-pencil
      label: false
      title: _("Edit %s %2s", ngettext('Version', 'Versions', 1), "[format| (%item%)]")
  dialogs: 
    versionsDel_dialog: &versionsDel_dialogLink 
      <<: *Versions
      controller: delete
      class: ui-silk-bin
      labelOption: false
      title: _("Delete %s", ngettext('Version', 'Versions', 1))
      description: _("Do you want to delete this %s?", ngettext('Version', 'Versions', 1))
      message: _("%s successfully deleted.", ngettext('Version', 'Versions', 1))
      multiItem: 1
      labelOnList: 1
testing: 
  _extends: production
staging: 
  _extends: production
development: 
  _extends: production
